jobs:

- job: Windows
  pool:
    vmImage: windows-2019
  strategy:
    maxParallel: 3
    matrix:
      stable:
        rustToolchain: stable
      beta:
        rustToolchain: beta
      nightly:
        rustToolchain: nightly
  steps:
  - template: ci/azure-test.yml
    parameters:
      rustToolchain: $(rustToolchain)

- job: Linux
  pool:
    vmImage: ubuntu-16.04
  strategy:
    maxParallel: 3
    matrix:
      stable:
        rustToolchain: stable
      beta:
        rustToolchain: beta
      nightly:
        rustToolchain: nightly
  steps:
  - template: ci/azure-test.yml
    parameters:
      rustToolchain: $(rustToolchain)
