[package]
name = "dxf"
version = "0.1.1"
authors = ["Brett V. Forsgren <brett.forsgren@outlook.com>"]
build = "build/build.rs"
description = "A rust crate for reading and writing DXF CAD files."
documentation = "https://docs.rs/dxf/"
repository = "https://github.com/IxMilia/dxf-rs"
readme = "README.md"
keywords = ["AutoCAD", "CAD", "DXF"]
license = "Apache-2.0"

[dependencies]
chrono = "0.2.25"
enum_primitive = "0.1.0"
itertools = "0.4.18"
num = "0.1.34"
time = "0.1"
uuid = { version = "0.3.0", features = ["use_std", "v4"] }

[build-dependencies]
xml-rs = "0.3.4"
xmltree = "0.3.2"
